name: plantrip
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  image_picker: ^1.2.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  uuid: ^4.5.2
  firebase_storage: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.4.0
  riverpod_generator: ^2.6.1


flutter:

  uses-material-design: true

  assets:
     - images/icon_edit.png
     - images/icon_time.png
     - images/7.png
